export const recipes = [
  {
    name: "Fried Egg",
    ingredients: [["egg", 1]],
    energy: 50,
    health: 22,
    sell: 35,
    sources: [["Upgraded farmhouse"]],
  },
  {
    name: "Omelet",
    ingredients: [
      ["Egg", 1],
      ["Milk", 1],
    ],
    energy: 100,
    health: 45,
    sell: 125,
    sources: [
      ["Queen of Sauce", 28],
      ["Saloon", 100],
    ],
  },
  {
    name: "Salad",
    ingredients: [
      ["Leek", 1],
      ["Dandelion", 1],
      ["Vinegar", 1],
    ],
    energy: 113,
    health: 50,
    sell: 110,
    sources: [["Emily", 3]],
  },
  {
    name: "Cheese Cauliflower",
    ingredients: [
      ["Cauliflower", 1],
      ["Cheese", 1],
    ],
    energy: 138,
    health: 62,
    sell: 300,
    sources: [["Pam", 3]],
  },
  {
    name: "Baked Fish",
    ingredients: [
      ["Sunfish", 1],
      ["Bream", 1],
      ["Wheat Flour", 1],
    ],
    energy: 75,
    health: 33,
    sell: 100,
    sources: [["Queen of Sauce", 35]],
  },
  {
    name: "Parsnip soup",
    ingredients: [
      ["Parsnip", 1],
      ["Milk", 1],
      ["Vinegar", 1],
    ],
    energy: 85,
    health: 38,
    sell: 120,
    sources: [["Caroline", 3]],
  },
  {
    name: "Vegetable Medley",
    ingredients: [
      ["Tomato", 1],
      ["Beet", 1],
    ],
    energy: 165,
    health: 74,
    sell: 120,
    sources: [["Caroline", 7]],
  },
  {
    name: "Complete Breakfast",
    ingredients: [
      ["Fried Egg", 1],
      ["Milk", 1],
      ["Hashbrowns", 1],
      ["Pancakes", 1],
    ],
    energy: 200,
    health: 90,
    stats: [
      ["Farming", 2, 420],
      ["Max Energy", 50, 420],
    ],
    sell: 350,
    sources: [["Queen of Sauce", 133]],
  },
  {
    name: "Fried Calamari",
    ingredients: [
      ["Squid", 1],
      ["Wheat Flour", 1],
      ["Oil", 1],
    ],
    energy: 80,
    health: 36,
    sell: 150,
    sources: [["Jodi", 3]],
  },
  {
    name: "Strange Bun",
    ingredients: [
      ["Wheat Flour", 1],
      ["Periwinkle", 1],
      ["Void Mayonnaise", 1],
    ],
    energy: 100,
    health: 45,
    sell: 225,
    sources: [["Shane", 7]],
  },
  {
    name: "Lucky Lunch",
    ingredients: [
      ["Sea Cucumber", 1],
      ["Tortilla", 1],
      ["Blue Jazz", 1],
    ],
    energy: 100,
    health: 45,
    stats: [["Luck", 3, 671]],
    sell: 250,
    sources: [["Queen of sauce", 140]],
  },
  {
    name: "Fried Mushroom",
    ingredients: [
      ["Common Mushroom", 1],
      ["Morel", 1],
      ["Oil", 1],
    ],
    energy: 135,
    health: 60,
    stats: [["Attack", 2, 140]],
    sell: 200,
    sources: [["Demetrius", 3]],
  },
  {
    name: "Pizza",
    ingredients: [
      ["Wheat Flour", 1],
      ["Tomato", 1],
      ["Cheese", 1],
    ],
    energy: 150,
    health: 67,
    sell: 300,
    sources: [
      ["Queen of Sauce", 119],
      ["Saloon", 150],
    ],
  },
  {
    name: "Bean Hotpot",
    ingredients: [["Green Bean", 2]],
    energy: 125,
    health: 56,
    stats: [
      ["Max Energy", 30, 420],
      ["Magnetism", 32, 420],
    ],
    sell: 100,
    sources: [["Clint", 7]],
  },
  {
    name: "Glazed Yams",
    ingredients: [
      ["Yam", 1],
      ["Sugar", 1],
    ],
    energy: 200,
    health: 90,
    sell: 200,
    sources: [["Queen of Sauce", 77]],
  },
  {
    name: "Carp Surprise",
    ingredients: [["Carp", 4]],
    energy: 90,
    health: 40,
    sell: 150,
    sources: [["Queen of Sauce", 147]],
  },
  {
    name: "Hashbrowns",
    ingredients: [
      ["Potato", 1],
      ["Oil", 1],
    ],
    energy: 90,
    health: 40,
    stats: [["Farming", 1, 335]],
    sell: 120,
    sources: [
      ["Queen of Sauce", 154],
      ["Saloon", 50],
    ],
  },
  {
    name: "Pancakes",
    ingredients: [
      ["Wheat Flour", 1],
      ["Egg", 1],
    ],
    energy: 90,
    health: 40,
    stats: [["Foraging", 2, 671]],
    sell: 80,
    sources: [
      ["Queen of Sauce", 42],
      ["Saloon", 100],
    ],
  },
  {
    name: "Salmon Dinner",
    ingredients: [
      ["Salmon", 1],
      ["Amaranth", 1],
      ["Kale", 1],
    ],
    energy: 125,
    health: 56,
    sell: 300,
    sources: [["Gus", 3]],
  },
  {
    name: "Fish Taco",
    ingredients: [
      ["Tuna", 1],
      ["Tortilla", 1],
      ["Red Cabbage", 1],
      ["Mayonnaise", 1],
    ],
    energy: 165,
    health: 74,
    stats: [["Fishing", 2, 420]],
    sell: 500,
    sources: [["Linus", 7]],
  },
  {
    name: "Crispy Bass",
    ingredients: [
      ["Largemouth Bass", 1],
      ["Wheat Flour", 1],
      ["Oil", 1],
    ],
    energy: 90,
    health: 40,
    stats: [["Magnetism", 64, 420]],
    sell: 150,
    sources: [["Kent", 3]],
  },
  {
    name: "Pepper Poppers",
    ingredients: [
      ["Hot Pepper", 1],
      ["Cheese", 1],
    ],
    energy: 130,
    health: 58,
    stats: [
      ["Farming", 2, 420],
      ["Speed", 1, 420],
    ],
    sell: 200,
    sources: [["Shane", 3]],
  },
  {
    name: "Bread",
    ingredients: [["Wheat Flour", 1]],
    energy: 50,
    health: 22,
    sell: 60,
    sources: [
      ["Queen of Sauce", 56],
      ["Saloon", 100],
    ],
  },
  {
    name: "Tom Kha Soup",
    ingredients: [
      ["Coconut", 1],
      ["Shrimp", 1],
      ["Common Mushroom", 1],
    ],
    energy: 175,
    health: 78,
    stats: [
      ["Farming", 2, 420],
      ["Max Energy", 30, 420],
    ],
    sell: 250,
    sources: [["Sandy", 7]],
  },
  {
    name: "Trout Soup",
    ingredients: [
      ["Rainbow Trout", 1],
      ["Green Algae", 1],
    ],
    energy: 100,
    health: 45,
    stats: [["Fishing", 1, 279]],
    sell: 100,
    sources: [["Queen of Sauce", 70]],
  },
  {
    name: "Chocolate Cake",
    ingredients: [
      ["Wheat Flour", 1],
      ["Sugar", 1],
      ["Egg", 1],
    ],
    energy: 150,
    health: 67,
    sell: 200,
    sources: [["Queen of Sauce", 98]],
  },
  {
    name: "Pink Cake",
    ingredients: [
      ["Melon", 1],
      ["Wheat Flour", 1],
      ["Sugar", 1],
      ["Egg", 1],
    ],
    energy: 250,
    health: 112,
    sell: 480,
    sources: [["Queen of Sauce", 161]],
  },
  {
    name: "Rhubarb Pie",
    ingredients: [
      ["Rhubarb", 1],
      ["Wheat Flour", 1],
      ["Sugar", 1],
    ],
    energy: 215,
    health: 96,
    sell: 400,
    sources: [["Marnie", 7]],
  },
  {
    name: "Cookie",
    ingredients: [
      ["Wheat Flour", 1],
      ["Sugar", 1],
      ["Egg", 1],
    ],
    energy: 90,
    health: 40,
    sell: 140,
    sources: [["Evelyn", 4, "event"]],
  },
  {
    name: "Spaghetti",
    ingredients: [
      ["Wheat Flour", 1],
      ["Tomato", 1],
    ],
    energy: 75,
    health: 33,
    sell: 120,
    sources: [["Lewis", 3]],
  },
  {
    name: "Fried Eel",
    ingredients: [
      ["Eel", 1],
      ["Oil", 1],
    ],
    energy: 75,
    health: 33,
    stats: [["Luck", 1, 420]],
    sell: 120,
    sources: [["George", 3]],
  },
  {
    name: "Spicy Eel",
    ingredients: [
      ["Eel", 1],
      ["Hot Pepper", 1],
    ],
    energy: 115,
    health: 51,
    stats: [
      ["Luck", 1, 420],
      ["Speed", 1, 420],
    ],
    sell: 175,
    sources: [["George", 7]],
  },
  {
    name: "Sashimi",
    ingredients: [["Any Fish", 1]],
    energy: 75,
    health: 33,
    sell: 75,
    sources: ["Linus", 3],
  },
  {
    name: "Maki Roll",
    ingredients: [
      ["Any Fish", 1],
      ["Seaweed", 1],
      ["Rice", 1],
    ],
    energy: 100,
    health: 45,
    sell: 220,
    sources: [
      ["Queen of Sauce", 49],
      ["Saloon", 300],
    ],
  },
  {
    name: "Tortilla",
    ingredients: [["Corn", 1]],
    energy: 50,
    health: 22,
    sell: 50,
    sources: [
      ["Queen of Sauce", 63],
      ["Saloon", 100],
    ],
  },
  {
    name: "Red Plate",
    ingredients: [
      ["Red Cabbage", 1],
      ["Radish", 1],
    ],
    energy: 240,
    health: 108,
    stats: [["Max Energy", 50, 210]],
    sell: 400,
    sources: [["Emily", 7]],
  },
  {
    name: "Eggplant Parmesan",
    ingredients: [
      ["Eggplant", 1],
      ["Tomato", 1],
    ],
    energy: 175,
    health: 78,
    stats: [
      ["Mining", 1, 279],
      ["Defense", 3, 279],
    ],
    sell: 200,
    sources: [["Lewis", 7]],
  },
  {
    name: "Rice Pudding",
    ingredients: [
      ["Milk", 1],
      ["Sugar", 1],
      ["Rice", 1],
    ],
    energy: 115,
    health: 51,
    sell: 260,
    sources: [["Evelyn", 7]],
  },
  {
    name: "Ice Cream",
    ingredients: [
      ["Milk", 1],
      ["Sugar", 1],
    ],
    energy: 100,
    health: 45,
    sell: 120,
    sources: [["Jodi", 7]],
  },
  {
    name: "Blueberry Tart",
    ingredients: [
      ["Blueberry", 1],
      ["Wheat Flour", 1],
      ["Sugar", 1],
      ["Egg", 1],
    ],
    energy: 125,
    health: 56,
    sell: 150,
    sources: [["Pierre", 3]],
  },
  {
    name: "Autumn's Bounty",
    ingredients: [
      ["Yam", 1],
      ["Pumpkin", 1],
    ],
    energy: 220,
    health: 99,
    stats: [
      ["Foraging", 2, 461],
      ["Defense", 2, 461],
    ],
    sell: 350,
    sources: [["Demetrius", 7]],
  },
  {
    name: "Pumpkin Soup",
    ingredients: [
      ["Pumpkin", 1],
      ["Milk", 1],
    ],
    energy: 200,
    health: 90,
    stats: [
      ["Defense", 2, 461],
      ["Luck", 2, 461],
    ],
    sell: 300,
    sources: [["Robin", 7]],
  },
  {
    name: "Super Meal",
    ingredients: [
      ["Bok Choy", 1],
      ["Cranberries", 1],
      ["Artichoke", 1],
    ],
    energy: 160,
    health: 72,
    stats: [
      ["Max Energy", 40, 210],
      ["Speed", 1, 210],
    ],
    sell: 220,
    sources: [["Kent", 7]],
  },
  {
    name: "Cranberry Sauce",
    ingredients: [
      ["Cranberries", 1],
      ["Sugar", 1],
    ],
    energy: 125,
    health: 56,
    stats: [["Mining", 2, 210]],
    sell: 120,
    sources: [["Gus", 7]],
  },
  {
    name: "Stuffing",
    ingredients: [
      ["Bread", 1],
      ["Cranberries", 1],
      ["Hazelnut", 1],
    ],
    energy: 170,
    health: 76,
    stats: [["Defense", 2, 335]],
    sell: 165,
    sources: [["Pam", 7]],
  },
  {
    name: "Farmer's Lunch",
    ingredients: [
      ["Omelet", 1],
      ["Parsnip", 1],
    ],
    energy: 200,
    health: 90,
    stats: [["Farming", 3, 335]],
    sell: 150,
    sources: [["Farming", 3]],
  },
  {
    name: "Survival Burger",
    ingredients: [
      ["Bread", 1],
      ["Cave Carrot", 1],
      ["Eggplant", 1],
    ],
    energy: 125,
    health: 56,
    stats: [["Foraging", 3, 335]],
    sell: 180,
    sources: [["Foraging", 2]],
  },
  {
    name: "Dish O' The Sea",
    ingredients: [
      ["Sardine", 2],
      ["Hashbrowns", 1],
    ],
    energy: 125,
    health: 56,
    stats: [["Fishing", 3, 335]],
    sell: 220,
    sources: [["Fishing", 3]],
  },
  {
    name: "Miner's Treat",
    ingredients: [
      ["Cave Carrot", 2],
      ["Sugar", 1],
      ["Milk", 1],
    ],
    energy: 125,
    health: 56,
    stats: [
      ["Mining", 3, 335],
      ["Magnetism", 32, 335],
    ],
    sell: 200,
    sources: [["Mining", 3]],
  },
  {
    name: "Roots Platter",
    ingredients: [
      ["Cave Carrot", 1],
      ["Winter Root", 1],
    ],
    energy: 125,
    health: 56,
    stats: [["Attack", 3, 335]],
    sell: 100,
    sources: [["Combat", 3]],
  },
  {
    name: "Triple Shot Espresso",
    ingredients: [["Coffee", 3]],
    energy: 8,
    health: 3,
    stats: [["Speed", 1, 252]],
    sell: 450,
    sources: [["Saloon", 5000]],
  },
  {
    name: "Seafoam Pudding",
    ingredients: [
      ["Flounder", 1],
      ["Midnight Carp", 1],
      ["Squid Ink", 1],
    ],
    energy: 175,
    health: 78,
    stats: [["Fishing", 4, 210]],
    sell: 300,
    sources: [["Fishing", 9]],
  },
  {
    name: "Algae Soup",
    ingredients: [["Green Algae", 4]],
    energy: 75,
    health: 33,
    sell: 100,
    sources: [["Clint", 3]],
  },
  {
    name: "Pale Broth",
    ingredients: [["White Algae", 2]],
    energy: 125,
    health: 56,
    sell: 150,
    sources: [["Marnie", 3]],
  },
  {
    name: "Plum Pudding",
    ingredients: [
      ["Wild Plum", 2],
      ["Wheat Flour", 1],
      ["Sugar", 1],
    ],
    energy: 175,
    health: 78,
    sell: 260,
    sources: [["Queen of Sauce", 91]],
  },
  {
    name: "Artichoke Dip",
    ingredients: [
      ["Artichoke", 1],
      ["Milk", 1],
    ],
    energy: 100,
    health: 45,
    sell: 210,
    sources: [["Queen of Sauce", 84]],
  },
  {
    name: "Stir Fry",
    ingredients: [
      ["Cave Carrot", 1],
      ["Common Mushroom", 1],
      ["Kale", 1],
      ["Oil", 1],
    ],
    energy: 200,
    health: 90,
    sell: 335,
    sources: [["Queen of Sauce", 7]],
  },
  {
    name: "Roasted Hazelnuts",
    ingredients: [["Hazelnut", 3]],
    energy: 175,
    health: 78,
    sell: 270,
    sources: [["Queen of Sauce", 168]],
  },
  {
    name: "Pumpkin Pie",
    ingredients: [
      ["Pumpkin", 1],
      ["Wheat Flour", 1],
      ["Milk", 1],
      ["Sugar", 1],
    ],
    energy: 225,
    health: 101,
    sell: 385,
    sources: [["Queen of Sauce", 105]],
  },
  {
    name: "Radish Salad",
    ingredients: [
      ["Oil", 1],
      ["Vinegar", 1],
      ["Radish", 1],
    ],
    energy: 200,
    health: 90,
    sell: 300,
    sources: [["Queen of Sauce", 21]],
  },
  {
    name: "Fruit Salad",
    ingredients: [
      ["Blueberry", 1],
      ["Melon", 1],
      ["Apricot", 1],
    ],
    energy: 263,
    health: 118,
    sell: 450,
    sources: [["Queen of Sauce", 175]],
  },
  {
    name: "Blackberry Cobbler",
    ingredients: [
      ["Blackberry", 2],
      ["Sugar", 1],
      ["Wheat Flour", 1],
    ],
    energy: 175,
    health: 78,
    sell: 260,
    sources: [["Queen of Sauce", 182]],
  },
  {
    name: "Cranberry Candy",
    ingredients: [
      ["Cranberries", 1],
      ["Apple", 1],
      ["Sugar", 1],
    ],
    energy: 125,
    health: 56,
    sell: 175,
    sources: [["Queen of Sauce", 112]],
  },
  {
    name: "Bruschetta",
    ingredients: [
      ["Bread", 1],
      ["Oil", 1],
      ["Tomato", 1],
    ],
    energy: 113,
    health: 50,
    sell: 210,
    sources: [["Queen of Sauce", 217]],
  },
  {
    name: "Coleslaw",
    ingredients: [
      ["Red Cabbage", 1],
      ["Vinegar", 1],
      ["Mayonnaise", 1],
    ],
    energy: 213,
    health: 95,
    sell: 345,
    sources: [["Queen of Sauce", 14]],
  },
  {
    name: "Fiddlehead Risotto",
    ingredients: [
      ["Oil", 1],
      ["Fiddlehead Fern", 1],
      ["Garlic", 1],
    ],
    energy: 225,
    health: 101,
    sell: 350,
    sources: [["Queen of Sauce", 196]],
  },
  {
    name: "Poppyseed Muffin",
    ingredients: [
      ["Poppy", 1],
      ["Wheat Flour", 1],
      ["Sugar", 1],
    ],
    energy: 150,
    health: 67,
    sell: 250,
    sources: [["Queen of Sauce", 203]],
  },
  {
    name: "Chowder",
    ingredients: [
      ["Clam", 1],
      ["Milk", 1],
    ],
    energy: 225,
    health: 101,
    stats: [["Fishing", 1, 1007]],
    sell: 135,
    sources: [["Willy", 3]],
  },
  {
    name: "Fish Stew",
    ingredients: [
      ["Crayfish", 1],
      ["Mussel", 1],
      ["Periwinkle", 1],
      ["Tomato", 1],
    ],
    energy: 225,
    health: 101,
    stats: [["Fishing", 3, 1007]],
    sell: 175,
    sources: [["Willy", 7]],
  },
  {
    name: "Escargot",
    ingredients: [
      ["Snail", 1],
      ["Garlic", 1],
    ],
    energy: 225,
    health: 101,
    stats: [["Fishing", 2, 1007]],
    sell: 125,
    sources: [["Willy", 5]],
  },
  {
    name: "Lobster Bisque",
    ingredients: [
      ["Lobster", 1],
      ["Milk", 1],
    ],
    energy: 225,
    health: 101,
    stats: [
      ["Fishing", 3, 1007],
      ["Max Energy", 50, 1007],
    ],
    sell: 205,
    sources: [
      ["Queen of Sauce", 210],
      ["Willy", 9],
    ],
  },
  {
    name: "Maple Bar",
    ingredients: [
      ["Maple Syrup", 1],
      ["Sugar", 1],
      ["Wheat Flour", 1],
    ],
    energy: 225,
    health: 101,
    stats: [
      ["Farming", 1, 1007],
      ["Fishing", 1, 1007],
      ["Mining", 1, 1007],
    ],
    sell: 300,
    sources: [["Queen of Sauce", 154]],
  },
  {
    name: "Crab Cakes",
    ingredients: [
      ["Crab", 1],
      ["Wheat Flour", 1],
      ["Egg", 1],
      ["Oil", 1],
    ],
    energy: 225,
    health: 101,
    stats: [
      ["Speed", 1, 1007],
      ["Defense", 1, 1007],
    ],
    sell: 275,
    sources: [["Queen of Sauce", 189]],
  },
  {
    name: "Shrimp Cocktail",
    ingredients: [
      ["Tomato", 1],
      ["Shrimp", 1],
      ["Wild Horseradish", 1],
    ],
    energy: 225,
    health: 101,
    stats: [
      ["Fishing", 1, 602],
      ["Luck", 1, 602],
    ],
    sell: 160,
    sources: [["Queen of Sauce", 224]],
  },
  {
    name: "Ginger Ale",
    ingredients: [
      ["Ginger", 3],
      ["Sugar", 1],
    ],
    energy: 63,
    health: 28,
    stats: [["Luck", 1, 300]],
    sell: 200,
    sources: [["Dwarf Shop Volcano Dungeon", 1000]],
  },
  {
    name: "Banana Pudding",
    ingredients: [
      ["Banana", 1],
      ["Milk", 1],
      ["Sugar", 1],
    ],
    energy: 125,
    health: 56,
    stats: [
      ["Mining", 1, 301],
      ["Luck", 1, 301],
      ["Defense", 1, 301],
    ],
    sell: 260,
    sources: [["Island Trader", "30 Bone Fragment"]],
  },
  {
    name: "Mango Sticky Rice",
    ingredients: [
      ["Mango", 1],
      ["Coconut", 1],
      ["Rice", 1],
    ],
    energy: 113,
    health: 50,
    stats: [["Defense", 3, 301]],
    sell: 250,
    sources: [["Leo", 7]],
  },
  {
    name: "Poi",
    ingredients: [["Taro Root", 4]],
    energy: 75,
    health: 33,
    sell: 400,
    sources: ["Leo", 3],
  },
  {
    name: "Tropical Curry",
    ingredients: [
      ["Coconut", 1],
      ["Pineapple", 1],
      ["Hot Pepper", 1],
    ],
    energy: 150,
    health: 67,
    stats: [["Foraging", 4, 301]],
    sell: 500,
    sources: [["Ginger Island Resort", 2000]],
  },
  {
    name: "Squid Ink Ravioli",
    ingredients: [
      ["Squid Ink", 1],
      ["Wheat Flour", 1],
      ["Tomato", 1],
    ],
    energy: 125,
    health: 56,
    stats: [
      ["Mining", 1, 279],
      ["Squid Ink Ravioli", undefined, 179],
    ],
    sell: 150,
    sources: [["Combat", 9]],
  },
];
export const animal = [
  {
    name: "Egg",
    energy: 25,
    health: 11,
    sources: "Chicken",
  },
  {
    name: "Large Egg",
    energy: 38,
    health: 17,
    sources: "Chicken (more friendship)",
  },
  {
    name: "Milk",
    energy: 38,
    health: 17,
    sources: "Cow",
  },
  {
    name: "Large Milk",
    energy: 50,
    health: 22,
    sources: "Cow (more friendship)",
  },
  {
    name: "Duck Egg",
    energy: 38,
    health: 17,
    sources: "Duck",
  },
  {
    name: "Void Egg",
    energy: 38,
    health: 17,
    sources: "Void Chicken",
  },
  {
    name: "Goat Milk",
    energy: 63,
    health: 28,
    sources: "Goat",
  },
  {
    name: "Large Goat Milk",
    energy: 88,
    health: 39,
    sources: "Goat (more friendship)",
  },
  {
    name: "Ostrich Egg",
    energy: 38,
    health: 17,
    sources: "Ostrich",
  },
  {
    name: "Golden Egg",
    energy: 25,
    health: 11,
    sources: [
      "Golden Chicken",
      "Marnie's Ranch for 100,000",
      "Qi's Walnut Room for 100",
      "Golden Witch event",
      "Fishing Treasure Chest 0.12%",
    ],
  },
  {
    name: "Roe",
    energy: 50,
    health: 22,
    sources: "Fish in Fish Pond",
  },
  {
    name: "Truffle",
    energy: 13,
    health: 5,
    sources: "Spawned by Pig on Farm",
  },
];
